# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sundew_ipc_v1_pb2 as sundew__ipc__v1__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sundew_ipc_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SundewGateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/sundew.ipc.v1.SundewGate/Connect',
                request_serializer=sundew__ipc__v1__pb2.ScoreEvent.SerializeToString,
                response_deserializer=sundew__ipc__v1__pb2.GateDecision.FromString,
                _registered_method=True)
        self.PushTelemetry = channel.unary_unary(
                '/sundew.ipc.v1.SundewGate/PushTelemetry',
                request_serializer=sundew__ipc__v1__pb2.TelemetryPush.SerializeToString,
                response_deserializer=sundew__ipc__v1__pb2.Acknowledge.FromString,
                _registered_method=True)


class SundewGateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SundewGateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=sundew__ipc__v1__pb2.ScoreEvent.FromString,
                    response_serializer=sundew__ipc__v1__pb2.GateDecision.SerializeToString,
            ),
            'PushTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTelemetry,
                    request_deserializer=sundew__ipc__v1__pb2.TelemetryPush.FromString,
                    response_serializer=sundew__ipc__v1__pb2.Acknowledge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sundew.ipc.v1.SundewGate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sundew.ipc.v1.SundewGate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SundewGate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sundew.ipc.v1.SundewGate/Connect',
            sundew__ipc__v1__pb2.ScoreEvent.SerializeToString,
            sundew__ipc__v1__pb2.GateDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sundew.ipc.v1.SundewGate/PushTelemetry',
            sundew__ipc__v1__pb2.TelemetryPush.SerializeToString,
            sundew__ipc__v1__pb2.Acknowledge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
