# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sundew_ipc_v1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sundew_ipc_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sundew_ipc_v1.proto\x12\rsundew.ipc.v1\"`\n\x0bInitRequest\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x02 \x01(\t\x12\x13\n\x0bsdk_version\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_hash\x18\x04 \x01(\t\"e\n\x0cInitResponse\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.sundew.ipc.v1.Status\x12\x1d\n\x15heartbeat_interval_ms\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\"\'\n\tFeatureKV\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"`\n\nScoreEvent\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x12*\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x18.sundew.ipc.v1.FeatureKV\"\xa1\x01\n\x0cGateDecision\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x17\n\x0fshould_activate\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x11\n\tthreshold\x18\x04 \x01(\x01\x12\x18\n\x10risk_probability\x18\x05 \x01(\x01\x12%\n\x06status\x18\x06 \x01(\x0e\x32\x15.sundew.ipc.v1.Status\"\x80\x01\n\rTelemetryPush\x12\x17\n\x0f\x61\x63tivation_rate\x18\x01 \x01(\x01\x12\x17\n\x0f\x61verage_power_w\x18\x02 \x01(\x01\x12\x15\n\renergy_buffer\x18\x03 \x01(\x01\x12\x15\n\rtemperature_c\x18\x04 \x01(\x01\x12\x0f\n\x07samples\x18\x05 \x01(\x04\"F\n\x0b\x41\x63knowledge\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.sundew.ipc.v1.Status*\x80\x01\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1a\n\x16STATUS_INVALID_PAYLOAD\x10\x02\x12\x1e\n\x1aSTATUS_UNSUPPORTED_FEATURE\x10\x03\x12\x13\n\x0fSTATUS_OVERLOAD\x10\x04\x32\x9e\x01\n\nSundewGate\x12\x45\n\x07\x43onnect\x12\x19.sundew.ipc.v1.ScoreEvent\x1a\x1b.sundew.ipc.v1.GateDecision(\x01\x30\x01\x12I\n\rPushTelemetry\x12\x1c.sundew.ipc.v1.TelemetryPush\x1a\x1a.sundew.ipc.v1.Acknowledgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sundew_ipc_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=746
  _globals['_STATUS']._serialized_end=874
  _globals['_INITREQUEST']._serialized_start=38
  _globals['_INITREQUEST']._serialized_end=134
  _globals['_INITRESPONSE']._serialized_start=136
  _globals['_INITRESPONSE']._serialized_end=237
  _globals['_FEATUREKV']._serialized_start=239
  _globals['_FEATUREKV']._serialized_end=278
  _globals['_SCOREEVENT']._serialized_start=280
  _globals['_SCOREEVENT']._serialized_end=376
  _globals['_GATEDECISION']._serialized_start=379
  _globals['_GATEDECISION']._serialized_end=540
  _globals['_TELEMETRYPUSH']._serialized_start=543
  _globals['_TELEMETRYPUSH']._serialized_end=671
  _globals['_ACKNOWLEDGE']._serialized_start=673
  _globals['_ACKNOWLEDGE']._serialized_end=743
  _globals['_SUNDEWGATE']._serialized_start=877
  _globals['_SUNDEWGATE']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
