name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    name: Build & Publish (PyPI)
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Build sdist & wheel
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # default repository is production PyPI
          skip-existing: true
          print-hash: true
          verbose: true
