name: Publish to PyPI

on:
  push:
    tags:
      - "v*"         # e.g., v0.1.2

permissions:
  id-token: write    # REQUIRED for PyPI Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      # Uses OIDC to authenticate with PyPI (no secret needed)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # If you also want to publish to TestPyPI, add a second job with repository-url
          # repository-url: https://test.pypi.org/legacy/
          verbose: true
