name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*"            # e.g. v0.1.28
  workflow_dispatch:

permissions:
  contents: read
  id-token: write       # REQUIRED for PyPI Trusted Publishing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Lint & typecheck (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install .[dev]
      - name: Ruff (lint)
        run: ruff check .
      - name: Ruff (format check)
        run: ruff format --check .
      - name: MyPy (src only)
        run: mypy src

  build-and-publish:
    name: Build & Publish (TestPyPI)
    needs: test
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Build sdist & wheel
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish to TestPyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          print-hash: true
          verbose: true
